/**
 * Metadata Markers for Synthetic Source Files
 * 
 * These markers are injected into generated source files to signal
 * that the code is synthetic and should be treated accordingly.
 */

/**
 * Standard metadata header for synthetic files
 */
export const SYNTHETIC_FILE_HEADER = `/**
 * [LSG-SYNTHETIC] This file was generated by Shannon's Local Source Generator
 * 
 * WARNING: This is NOT actual source code from the target application.
 * It is a synthetic reconstruction based on external reconnaissance.
 * 
 * Treat all internal logic as HYPOTHETICAL.
 * Test actual HTTP behavior, not code paths.
 * 
 * Generated: ${new Date().toISOString()}
 */

`;

/**
 * Get route file header
 */
export function getRouteHeader(endpoint) {
    return `/**
 * [LSG-SYNTHETIC] Synthetic route file
 * [LSG-INFERRED] Route inferred from: ${endpoint.url || endpoint.path}
 * [LSG-ESTIMATED] HTTP method: ${endpoint.method || 'GET'} (estimated)
 * 
 * Parameters discovered: ${JSON.stringify(endpoint.params || {})}
 */

`;
}

/**
 * Get model file header  
 */
export function getModelHeader(modelName) {
    return `/**
 * [LSG-SYNTHETIC] Synthetic model file
 * [LSG-WARNING] Schema is HYPOTHETICAL - inferred from form analysis
 * 
 * Model: ${modelName}
 * 
 * Field types are ESTIMATED based on:
 * - Input field names
 * - Form validation patterns
 * - Common naming conventions
 */

`;
}

/**
 * Get security-relevant code marker
 */
export function getSecurityWarning(vulnType) {
    return `  // [LSG-WARNING] ${vulnType} candidate - REQUIRES BLACK-BOX TESTING
  // Do not trust this implementation - test actual HTTP behavior
`;
}

/**
 * Get parameter type annotation
 */
export function getParamAnnotation(paramName, inference) {
    const lines = [
        `  // [LSG-ESTIMATED] Parameter: ${paramName}`,
        `  // Type: ${inference.type}${inference.format ? ` (${inference.format})` : ''}`,
    ];

    if (inference.isSecurityRelevant) {
        lines.push(`  // [LSG-WARNING] Security-relevant: ${inference.candidateFor.join(', ')}`);
    }

    return lines.join('\n') + '\n';
}

/**
 * Pre-recon deliverable metadata section
 */
export const PRERECON_METADATA = `
---

## ⚠️ Synthetic Source Metadata

This analysis is based on **synthetic source code** generated by the Local Source Generator.

### Reliability Indicators

| Component | Confidence | Source |
|:----------|:-----------|:-------|
| Endpoints | HIGH | Crawled from target |
| Parameters | MEDIUM | Observed in requests |
| Route logic | LOW | Inferred/hypothetical |
| DB queries | LOW | Naming heuristics |
| Auth flow | MEDIUM | Form analysis |

### Testing Recommendations

1. **Prioritize black-box testing** over code review
2. **Verify endpoints** actually exist before testing
3. **Use HTTP tools** (curl, Playwright) for validation
4. **Don't trust code paths** — test actual behavior

---
`;

/**
 * Check if a file contains synthetic markers
 */
export function isSyntheticFile(content) {
    return content.includes('[LSG-SYNTHETIC]') ||
        content.includes('[LSG-INFERRED]') ||
        content.includes('[LSG-WARNING]');
}
